### ISSUE TITLE
Newbies encounter problems accessing

### ISSUE THREAD

**Issue by submarineCluster** [statsig-io/cpp-server-sdk#1]
I connected according to the instructions of https://docs.statsig.com/server/cppSDK, but an error was reported during the make link. I am a new user to cpp cmake. Can you provide a normal access example warehouse for learning? First Thanks

error message
`Scanning dependencies of target statsig_sdk
[  9%] Building CXX object CMakeFiles/statsig_sdk.dir/main.cpp.o
/Users/shaohui/Code/cpp/statsig_sdk/main.cpp:3:10: fatal error: 'statsig.h' file not found
#include <statsig.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/statsig_sdk.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/statsig_sdk.dir/all] Error 2
make: *** [all] Error 2

`

cmakelists.txt

`cmake_minimum_required(VERSION 3.11)
#
include(FetchContent)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/statsig.cmake)

option(STATSIG_BUILD_TESTS "Compile with unit tests" OFF)
option(STATSIG_INCLUDE_MAXMINDDB "Include the 3rd party library maxminddb. (Disable if country lookup is not needed)" ON)

project(statsig_sdk)

set(CMAKE_CXX_STANDARD 20)

add_executable(statsig_sdk main.cpp)

target_link_libraries(statsig_sdk statsig)`

main.cpp

`#include <iostream>

#include <statsig.h>

int main() {
    std::cout << "Hello, World!" << std::endl;
    statsig::initialize('server-secret-key');
    return 0;
}
`

I don't know how to solve this error. Please help me when you have time.

**Comment by kenny-statsig** [comment]
Hey there, thanks for checking out the C++ SDK!
I believe the issue is that you are linking the Statsig library incorrectly. The target name should be `Statsig::cpp` not `statsig`

```target_link_libraries(statsig_sdk Statsig::cpp)```

**Comment by submarineCluster** [comment]
Thank you very much, it works now
